#!/usr/bin/env bash
# Platform bootstrap installer — run as root on a fresh VPS
# curl -fsSL https://raw.githubusercontent.com/support-collabrains/platform-/main/install.sh | bash
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[platform]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*"; }
die()   { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

# ── Prereqs ──────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Run as root (sudo bash install.sh)"
command -v docker &>/dev/null || die "Docker is not installed. Install it first: https://docs.docker.com/engine/install/"
docker compose version &>/dev/null 2>&1 || \
  die "Docker Compose v2 not found. Update Docker or install the plugin."
command -v openssl &>/dev/null || die "openssl not found. Install it first."

INSTALL_DIR="${PLATFORM_DIR:-/srv/platform}"

# ── Clone or use current directory ───────────────────────────────────────
if [[ ! -f "$INSTALL_DIR/docker-compose.yml" ]]; then
  info "Downloading platform to $INSTALL_DIR..."
  mkdir -p "$INSTALL_DIR"
  REPO_URL="${PLATFORM_REPO:-https://github.com/support-collabrains/platform-}"
  git clone --depth 1 "$REPO_URL" "$INSTALL_DIR" 2>/dev/null || \
    die "Could not clone $REPO_URL — set PLATFORM_REPO env var to your repo URL"
fi

cd "$INSTALL_DIR"

# ── Generate secrets ──────────────────────────────────────────────────────
info "Generating secrets..."
gen() { openssl rand -hex "${1:-32}"; }

ENV_FILE="$INSTALL_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists — skipping secret generation. Remove it to regenerate."
else
  cat > "$ENV_FILE" <<EOF
# Generated by platform install.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do NOT commit this file.

DB_PASSWORD=$(gen)
AUTHENTIK_DB_PASSWORD=$(gen)
AUTHENTIK_SECRET_KEY=$(gen 64)
AUTHENTIK_BOOTSTRAP_TOKEN=$(gen 64)
INTERNAL_API_SECRET=$(gen 64)
OAUTH_CLIENT_SECRET=$(gen)
PAPERLESS_OIDC_CLIENT_SECRET=$(gen)
PAPERLESS_SECRET_KEY=$(gen 64)

# Set these before starting:
PRIMARY_DOMAIN=
MAIL_DOMAIN=
ADMIN_EMAIL=
ADMIN_PASSWORD=
MAILCOW_API_KEY=
EOF
  info "Secrets written to $ENV_FILE"
fi

# ── Validate required env vars ─────────────────────────────────────────────
# shellcheck source=/dev/null
source "$ENV_FILE"
errors=0
for var in PRIMARY_DOMAIN MAIL_DOMAIN ADMIN_EMAIL ADMIN_PASSWORD; do
  if [[ -z "${!var:-}" ]]; then
    warn "Missing required variable: $var — edit $ENV_FILE and re-run"
    errors=$((errors + 1))
  fi
done

if [[ $errors -gt 0 ]]; then
  echo ""
  info "Edit $ENV_FILE to fill in the required values, then re-run this script."
  exit 1
fi

# ── Create directory layout ────────────────────────────────────────────────
info "Creating directory layout..."
mkdir -p "$INSTALL_DIR"/{config/traefik,data,backups,secrets,core}
chmod 700 "$INSTALL_DIR/secrets"

# ── Traefik static config ─────────────────────────────────────────────────
TRAEFIK_YML="$INSTALL_DIR/config/traefik/traefik.yml"
if [[ ! -f "$TRAEFIK_YML" ]]; then
  info "Writing Traefik static config..."
  cat > "$TRAEFIK_YML" <<EOF
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ADMIN_EMAIL}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
    network: platform
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: false

log:
  level: INFO
EOF
  info "traefik.yml written"
else
  warn "traefik.yml already exists — skipping"
fi

# ── Traefik dynamic config: mailcow route ────────────────────────────────────
mkdir -p "$INSTALL_DIR/config/traefik/dynamic"
MAILCOW_DYNAMIC="$INSTALL_DIR/config/traefik/dynamic/mailcow.yml"
if [[ ! -f "$MAILCOW_DYNAMIC" ]]; then
  info "Writing Traefik dynamic mailcow route..."
  cat > "$MAILCOW_DYNAMIC" <<EOF
http:
  routers:
    mailcow:
      rule: "Host(\`${MAILCOW_HOSTNAME}\`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: mailcow-svc

  services:
    mailcow-svc:
      loadBalancer:
        servers:
          - url: "http://nginx-mailcow:8080"
EOF
  info "mailcow dynamic route written"
fi

# ── Mailcow setup ─────────────────────────────────────────────────────────
MAILCOW_DIR="$INSTALL_DIR/core/mailcow"

if [[ ! -f "$MAILCOW_DIR/docker-compose.yml" ]]; then
  info "Cloning mailcow-dockerized..."
  git clone --depth 1 https://github.com/mailcow/mailcow-dockerized "$MAILCOW_DIR"
else
  info "mailcow-dockerized already present, skipping clone"
fi

MAILCOW_CONF="$MAILCOW_DIR/mailcow.conf"
if [[ ! -f "$MAILCOW_CONF" ]]; then
  info "Generating mailcow.conf..."
  MAIL_HOSTNAME="${MAIL_DOMAIN:-mail.${PRIMARY_DOMAIN}}"
  REDISPASS="$(gen)"
  cat > "$MAILCOW_CONF" <<EOF
# Generated by platform install.sh
MAILCOW_HOSTNAME=${MAIL_HOSTNAME}
MAILCOW_BRANCH=master
DBNAME=mailcow
DBUSER=mailcow
DBPASS=$(gen)
DBROOT=$(gen)
REDISPASS=${REDISPASS}
HTTP_PORT=8080
HTTP_BIND=127.0.0.1
HTTPS_PORT=8443
HTTPS_BIND=127.0.0.1
SMTP_PORT=25
SMTPS_PORT=465
SUBMISSION_PORT=587
IMAP_PORT=143
IMAPS_PORT=993
POP_PORT=110
POPS_PORT=995
SIEVE_PORT=4190
TZ=${TIMEZONE:-UTC}
SKIP_LETS_ENCRYPT=y
SKIP_SOGO=n
SKIP_CLAMD=n
SKIP_OLEFY=n
ALLOW_ADMIN_EMAIL_LOGIN=n
MAILCOW_PASS_SCHEME=BLF-CRYPT
IPV4_NETWORK=172.22.1
IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
ACL_ANYONE=disallow
WATCHDOG_NOTIFY_EMAIL=
WATCHDOG_NOTIFY_BAN_TRESHOLD=3
WATCHDOG_SUBJECT=Mailcow Warning
SQL_PORT=13306
SOLR_PORT=18983
REDIS_PORT=7654
EOF
  # mailcow expects .env to match mailcow.conf
  ln -sf "$MAILCOW_CONF" "$MAILCOW_DIR/.env" 2>/dev/null || cp "$MAILCOW_CONF" "$MAILCOW_DIR/.env"
  info "mailcow.conf written"
else
  warn "mailcow.conf already exists — skipping"
fi

# ── Traefik override for mailcow (Traefik labels + platform network) ──────
OVERRIDE="$MAILCOW_DIR/traefik.override.yml"
if [[ ! -f "$OVERRIDE" ]]; then
  info "Writing mailcow Traefik override..."
  MAIL_HOSTNAME="${MAIL_DOMAIN:-mail.${PRIMARY_DOMAIN}}"
  cat > "$OVERRIDE" <<'EOF'
# Merged on top of mailcow's docker-compose.yml via the include: directive.
# Attaches nginx-mailcow to the platform network so Traefik can route it.
networks:
  platform:
    external: true

services:
  nginx-mailcow:
    networks:
      mailcow-network: {}
      platform: {}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=platform"
      - "traefik.http.routers.mailcow.rule=Host(`${MAILCOW_HOSTNAME}`)"
      - "traefik.http.routers.mailcow.entrypoints=websecure"
      - "traefik.http.routers.mailcow.tls.certresolver=letsencrypt"
      - "traefik.http.services.mailcow.loadbalancer.server.port=8080"
EOF
  info "traefik.override.yml written"
else
  warn "traefik.override.yml already exists — skipping"
fi

# ── Self-signed TLS cert for mailcow's nginx (Traefik handles public TLS) ──
SSL_DIR="$MAILCOW_DIR/data/assets/ssl"
mkdir -p "$SSL_DIR"
if [[ ! -f "$SSL_DIR/cert.pem" ]]; then
  info "Generating self-signed cert for mailcow nginx..."
  MAIL_HOSTNAME="${MAIL_DOMAIN:-mail.${PRIMARY_DOMAIN}}"
  openssl req -x509 -newkey rsa:4096 \
    -keyout "$SSL_DIR/key.pem" \
    -out    "$SSL_DIR/cert.pem" \
    -days 3650 -nodes \
    -subj "/CN=${MAIL_HOSTNAME}" 2>/dev/null
  info "Self-signed cert written to $SSL_DIR"
fi

if [[ ! -f "$SSL_DIR/dhparams.pem" ]]; then
  info "Generating DH parameters (this takes ~30s)..."
  openssl dhparam -out "$SSL_DIR/dhparams.pem" 2048 2>/dev/null
  info "DH parameters written"
fi

# ── Pull images & build ────────────────────────────────────────────────────
info "Pulling and building platform images (this takes a few minutes)..."
docker compose pull --ignore-buildable 2>/dev/null || true
docker compose build

# ── Start ─────────────────────────────────────────────────────────────────
info "Starting platform..."
docker compose up -d

# ── Wait for API ───────────────────────────────────────────────────────────
info "Waiting for API to be ready..."
timeout=90
until docker compose exec -T api wget -qO- http://localhost:3001/bootstrap/state &>/dev/null 2>&1; do
  timeout=$((timeout - 3))
  [[ $timeout -le 0 ]] && die "API did not start within 90s — check: docker compose logs api"
  sleep 3
done

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Platform installed successfully${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Open the setup wizard in your browser:"
echo ""
echo "    https://portal.${PRIMARY_DOMAIN}/setup"
echo ""
