// portal/app/dashboard/lang.ts
export type Lang = 'nl' | 'de' | 'en';

const nl = {
  titleHome: 'Home',
  titleMail: 'Mail',
  titleDocs: 'Documenten',
  titleProfile: 'Profiel',
  titleFallback: 'CollaBrains',
  navHome: 'Home',
  navMail: 'Mail',
  navDocs: 'Docs',
  navProfile: 'Profiel',
  welcome: (name: string) => `Welkom, ${name}`,
  overview: 'Hier is je overzicht',
  statDocs: 'Documenten',
  statMail: 'Ongelezen mail',
  statProcessing: 'In verwerking',
  recentActivity: 'Recente activiteit',
  noActivity: 'Nog geen activiteit',
  statusDone: 'Samenvatting verzonden',
  statusProcessing: 'Bezig met verwerken',
  statusPending: 'Wacht op verwerking',
  statusFailed: 'Mislukt',
  timeJustNow: 'zojuist',
  timeMinutes: (m: number) => `${m}m geleden`,
  timeHours: (h: number) => `${h}u geleden`,
  timeDays: (d: number) => `${d}d geleden`,
  searchPlaceholder: 'Zoeken...',
  noResults: 'Geen resultaten',
  noDocs: 'Geen documenten',
  sectionNotifications: 'Meldingen',
  saving: 'opslaan…',
  prefSignalNotify: 'Signal-meldingen',
  prefSignalNotifyDesc: 'Melding bij nieuw document',
  prefDigest: 'Digest-modus',
  prefDigestDesc: 'Dagelijks overzicht i.p.v. direct',
  sectionLanguage: 'Taal',
  adminSettings: 'Beheerdersinstellingen',
  adminSettingsDesc: 'Gebruikers, tickets, configuratie',
  logout: 'Uitloggen',
  mailNoMessages: 'Geen berichten',
  mailLoading: 'Laden…',
  mailConnectionError: 'Verbindingsfout',
  mailLoadError: 'Kon berichten niet laden',
  mailSelectMessage: 'Selecteer een bericht',
  mailUnknown: '(onbekend)',
  mailNoSubject: '(geen onderwerp)',
  mailNoContent: '(geen inhoud)',
  mailFrom: 'Van:',
  mailTo: 'Aan:',
  mailCc: 'CC:',
  mailMoveToTrash: 'Naar prullenbak',
  mailDeleteForever: 'Definitief verwijderen',
};

const de: typeof nl = {
  titleHome: 'Startseite',
  titleMail: 'Mail',
  titleDocs: 'Dokumente',
  titleProfile: 'Profil',
  titleFallback: 'CollaBrains',
  navHome: 'Startseite',
  navMail: 'Mail',
  navDocs: 'Dokumente',
  navProfile: 'Profil',
  welcome: (name: string) => `Willkommen, ${name}`,
  overview: 'Hier ist deine Übersicht',
  statDocs: 'Dokumente',
  statMail: 'Ungelesene Mails',
  statProcessing: 'In Bearbeitung',
  recentActivity: 'Letzte Aktivität',
  noActivity: 'Noch keine Aktivität',
  statusDone: 'Zusammenfassung gesendet',
  statusProcessing: 'Wird verarbeitet',
  statusPending: 'Wartet auf Verarbeitung',
  statusFailed: 'Fehlgeschlagen',
  timeJustNow: 'gerade eben',
  timeMinutes: (m: number) => `vor ${m} Min.`,
  timeHours: (h: number) => `vor ${h} Std.`,
  timeDays: (d: number) => `vor ${d} Tagen`,
  searchPlaceholder: 'Suchen...',
  noResults: 'Keine Ergebnisse',
  noDocs: 'Keine Dokumente',
  sectionNotifications: 'Benachrichtigungen',
  saving: 'speichern…',
  prefSignalNotify: 'Signal-Benachrichtigungen',
  prefSignalNotifyDesc: 'Benachrichtigung bei neuem Dokument',
  prefDigest: 'Digest-Modus',
  prefDigestDesc: 'Tägliche Übersicht statt sofort',
  sectionLanguage: 'Sprache',
  adminSettings: 'Admineinstellungen',
  adminSettingsDesc: 'Benutzer, Tickets, Konfiguration',
  logout: 'Abmelden',
  mailNoMessages: 'Keine Nachrichten',
  mailLoading: 'Laden…',
  mailConnectionError: 'Verbindungsfehler',
  mailLoadError: 'Nachrichten konnten nicht geladen werden',
  mailSelectMessage: 'Nachricht auswählen',
  mailUnknown: '(unbekannt)',
  mailNoSubject: '(kein Betreff)',
  mailNoContent: '(kein Inhalt)',
  mailFrom: 'Von:',
  mailTo: 'An:',
  mailCc: 'CC:',
  mailMoveToTrash: 'In Papierkorb',
  mailDeleteForever: 'Endgültig löschen',
};

const en: typeof nl = {
  titleHome: 'Home',
  titleMail: 'Mail',
  titleDocs: 'Documents',
  titleProfile: 'Profile',
  titleFallback: 'CollaBrains',
  navHome: 'Home',
  navMail: 'Mail',
  navDocs: 'Docs',
  navProfile: 'Profile',
  welcome: (name: string) => `Welcome, ${name}`,
  overview: 'Here is your overview',
  statDocs: 'Documents',
  statMail: 'Unread mail',
  statProcessing: 'Processing',
  recentActivity: 'Recent activity',
  noActivity: 'No activity yet',
  statusDone: 'Summary sent',
  statusProcessing: 'Processing',
  statusPending: 'Waiting to process',
  statusFailed: 'Failed',
  timeJustNow: 'just now',
  timeMinutes: (m: number) => `${m}m ago`,
  timeHours: (h: number) => `${h}h ago`,
  timeDays: (d: number) => `${d}d ago`,
  searchPlaceholder: 'Search...',
  noResults: 'No results',
  noDocs: 'No documents',
  sectionNotifications: 'Notifications',
  saving: 'saving…',
  prefSignalNotify: 'Signal notifications',
  prefSignalNotifyDesc: 'Alert on new document',
  prefDigest: 'Digest mode',
  prefDigestDesc: 'Daily digest instead of instant',
  sectionLanguage: 'Language',
  adminSettings: 'Admin settings',
  adminSettingsDesc: 'Users, tickets, configuration',
  logout: 'Sign out',
  mailNoMessages: 'No messages',
  mailLoading: 'Loading…',
  mailConnectionError: 'Connection error',
  mailLoadError: 'Could not load messages',
  mailSelectMessage: 'Select a message',
  mailUnknown: '(unknown)',
  mailNoSubject: '(no subject)',
  mailNoContent: '(no content)',
  mailFrom: 'From:',
  mailTo: 'To:',
  mailCc: 'CC:',
  mailMoveToTrash: 'Move to trash',
  mailDeleteForever: 'Delete permanently',
};

export const translations: Record<Lang, typeof nl> = { nl, de, en };
export type T = typeof nl;
