// portal/app/dashboard/lang.ts
export type Lang = 'nl' | 'de' | 'en';

const nl = {
  titleHome: 'Home',
  titleMail: 'Mail',
  titleDocs: 'Documenten',
  titleProfile: 'Profiel',
  titleTasks: 'Taken',
  titleCalendar: 'Agenda',
  titlePhotos: "Foto's",
  titleFallback: 'CollaBrains',
  navHome: 'Home',
  navMail: 'Mail',
  navDocs: 'Docs',
  navProfile: 'Profiel',
  navTasks: 'Taken',
  welcome: (name: string) => `Welkom, ${name}`,
  overview: 'Hier is je overzicht',
  statDocs: 'Documenten',
  statMail: 'Ongelezen mail',
  statProcessing: 'In verwerking',
  statTasks: 'Open taken',
  recentActivity: 'Recente activiteit',
  noActivity: 'Nog geen activiteit',
  statusDone: 'Samenvatting verzonden',
  statusProcessing: 'Bezig met verwerken',
  statusPending: 'Wacht op verwerking',
  statusFailed: 'Mislukt',
  timeJustNow: 'zojuist',
  timeMinutes: (m: number) => `${m}m geleden`,
  timeHours: (h: number) => `${h}u geleden`,
  timeDays: (d: number) => `${d}d geleden`,
  searchPlaceholder: 'Zoeken...',
  noResults: 'Geen resultaten',
  noDocs: 'Geen documenten',
  sectionNotifications: 'Meldingen',
  saving: 'opslaan…',
  prefSignalNotify: 'Signal-meldingen',
  prefSignalNotifyDesc: 'Melding bij nieuw document',
  prefDigest: 'Digest-modus',
  prefDigestDesc: 'Dagelijks overzicht i.p.v. direct',
  sectionLanguage: 'Taal',
  adminSettings: 'Beheerdersinstellingen',
  adminSettingsDesc: 'Gebruikers, tickets, configuratie',
  logout: 'Uitloggen',
  mailNoMessages: 'Geen berichten',
  mailLoading: 'Laden…',
  mailConnectionError: 'Verbindingsfout',
  mailLoadError: 'Kon berichten niet laden',
  mailSelectMessage: 'Selecteer een bericht',
  mailUnknown: '(onbekend)',
  mailNoSubject: '(geen onderwerp)',
  mailNoContent: '(geen inhoud)',
  mailFrom: 'Van:',
  mailTo: 'Aan:',
  mailCc: 'CC:',
  mailMoveToTrash: 'Naar prullenbak',
  mailDeleteForever: 'Definitief verwijderen',
  // Tasks
  tasksOpen: 'Open taken',
  tasksDone: 'Afgerond',
  tasksEmpty: 'Geen openstaande taken',
  tasksDoneEmpty: 'Nog geen afgeronde taken',
  tasksMarkDone: 'Afgerond',
  tasksDelete: 'Verwijder',
  tasksDue: 'Vervaldatum',
  tasksOverdue: 'Te laat',
  tasksAddSignal: 'Stuur /taak <beschrijving> op Signal om een taak aan te maken.',
  // Calendar
  calendarToday: 'Vandaag',
  calendarThisWeek: 'Deze week',
  calendarNoEvents: 'Geen evenementen',
  calendarAdd: 'Toevoegen',
  calendarAllDay: 'Hele dag',
  // Docs
  noArchive: 'Geen archief beschikbaar',
  selectCategory: 'Selecteer een categorie',
  // Error handling
  errorRetry: 'Opnieuw proberen',
  errorServiceUnavailable: 'Service niet beschikbaar',
  errorLoading: 'Fout bij laden',
};

const de: typeof nl = {
  titleHome: 'Startseite',
  titleMail: 'Mail',
  titleDocs: 'Dokumente',
  titleProfile: 'Profil',
  titleTasks: 'Aufgaben',
  titleCalendar: 'Kalender',
  titlePhotos: 'Fotos',
  titleFallback: 'CollaBrains',
  navHome: 'Startseite',
  navMail: 'Mail',
  navDocs: 'Dokumente',
  navProfile: 'Profil',
  navTasks: 'Aufgaben',
  welcome: (name: string) => `Willkommen, ${name}`,
  overview: 'Hier ist deine Übersicht',
  statDocs: 'Dokumente',
  statMail: 'Ungelesene Mails',
  statProcessing: 'In Bearbeitung',
  statTasks: 'Offene Aufgaben',
  recentActivity: 'Letzte Aktivität',
  noActivity: 'Noch keine Aktivität',
  statusDone: 'Zusammenfassung gesendet',
  statusProcessing: 'Wird verarbeitet',
  statusPending: 'Wartet auf Verarbeitung',
  statusFailed: 'Fehlgeschlagen',
  timeJustNow: 'gerade eben',
  timeMinutes: (m: number) => `vor ${m} Min.`,
  timeHours: (h: number) => `vor ${h} Std.`,
  timeDays: (d: number) => `vor ${d} Tagen`,
  searchPlaceholder: 'Suchen...',
  noResults: 'Keine Ergebnisse',
  noDocs: 'Keine Dokumente',
  sectionNotifications: 'Benachrichtigungen',
  saving: 'speichern…',
  prefSignalNotify: 'Signal-Benachrichtigungen',
  prefSignalNotifyDesc: 'Benachrichtigung bei neuem Dokument',
  prefDigest: 'Digest-Modus',
  prefDigestDesc: 'Tägliche Übersicht statt sofort',
  sectionLanguage: 'Sprache',
  adminSettings: 'Admineinstellungen',
  adminSettingsDesc: 'Benutzer, Tickets, Konfiguration',
  logout: 'Abmelden',
  mailNoMessages: 'Keine Nachrichten',
  mailLoading: 'Laden…',
  mailConnectionError: 'Verbindungsfehler',
  mailLoadError: 'Nachrichten konnten nicht geladen werden',
  mailSelectMessage: 'Nachricht auswählen',
  mailUnknown: '(unbekannt)',
  mailNoSubject: '(kein Betreff)',
  mailNoContent: '(kein Inhalt)',
  mailFrom: 'Von:',
  mailTo: 'An:',
  mailCc: 'CC:',
  mailMoveToTrash: 'In Papierkorb',
  mailDeleteForever: 'Endgültig löschen',
  tasksOpen: 'Offene Aufgaben',
  tasksDone: 'Erledigt',
  tasksEmpty: 'Keine offenen Aufgaben',
  tasksDoneEmpty: 'Noch keine erledigten Aufgaben',
  tasksMarkDone: 'Erledigt',
  tasksDelete: 'Löschen',
  tasksDue: 'Fällig',
  tasksOverdue: 'Überfällig',
  tasksAddSignal: 'Sende /aufgabe <beschreibung> auf Signal um eine Aufgabe zu erstellen.',
  calendarToday: 'Heute',
  calendarThisWeek: 'Diese Woche',
  calendarNoEvents: 'Keine Termine',
  calendarAdd: 'Hinzufügen',
  calendarAllDay: 'Ganzer Tag',
  noArchive: 'Kein Archiv verfügbar',
  selectCategory: 'Kategorie auswählen',
  // Error handling
  errorRetry: 'Erneut versuchen',
  errorServiceUnavailable: 'Dienst nicht verfügbar',
  errorLoading: 'Fehler beim Laden',
};

const en: typeof nl = {
  titleHome: 'Home',
  titleMail: 'Mail',
  titleDocs: 'Documents',
  titleProfile: 'Profile',
  titleTasks: 'Tasks',
  titleCalendar: 'Calendar',
  titlePhotos: 'Photos',
  titleFallback: 'CollaBrains',
  navHome: 'Home',
  navMail: 'Mail',
  navDocs: 'Docs',
  navProfile: 'Profile',
  navTasks: 'Tasks',
  welcome: (name: string) => `Welcome, ${name}`,
  overview: 'Here is your overview',
  statDocs: 'Documents',
  statMail: 'Unread mail',
  statProcessing: 'Processing',
  statTasks: 'Open tasks',
  recentActivity: 'Recent activity',
  noActivity: 'No activity yet',
  statusDone: 'Summary sent',
  statusProcessing: 'Processing',
  statusPending: 'Waiting to process',
  statusFailed: 'Failed',
  timeJustNow: 'just now',
  timeMinutes: (m: number) => `${m}m ago`,
  timeHours: (h: number) => `${h}h ago`,
  timeDays: (d: number) => `${d}d ago`,
  searchPlaceholder: 'Search...',
  noResults: 'No results',
  noDocs: 'No documents',
  sectionNotifications: 'Notifications',
  saving: 'saving…',
  prefSignalNotify: 'Signal notifications',
  prefSignalNotifyDesc: 'Alert on new document',
  prefDigest: 'Digest mode',
  prefDigestDesc: 'Daily digest instead of instant',
  sectionLanguage: 'Language',
  adminSettings: 'Admin settings',
  adminSettingsDesc: 'Users, tickets, configuration',
  logout: 'Sign out',
  mailNoMessages: 'No messages',
  mailLoading: 'Loading…',
  mailConnectionError: 'Connection error',
  mailLoadError: 'Could not load messages',
  mailSelectMessage: 'Select a message',
  mailUnknown: '(unknown)',
  mailNoSubject: '(no subject)',
  mailNoContent: '(no content)',
  mailFrom: 'From:',
  mailTo: 'To:',
  mailCc: 'CC:',
  mailMoveToTrash: 'Move to trash',
  mailDeleteForever: 'Delete permanently',
  tasksOpen: 'Open tasks',
  tasksDone: 'Done',
  tasksEmpty: 'No open tasks',
  tasksDoneEmpty: 'No completed tasks yet',
  tasksMarkDone: 'Mark done',
  tasksDelete: 'Delete',
  tasksDue: 'Due',
  tasksOverdue: 'Overdue',
  tasksAddSignal: 'Send /task <description> on Signal to create a task.',
  calendarToday: 'Today',
  calendarThisWeek: 'This week',
  calendarNoEvents: 'No events',
  calendarAdd: 'Add',
  calendarAllDay: 'All day',
  noArchive: 'No archive available',
  selectCategory: 'Select a category',
  // Error handling
  errorRetry: 'Try again',
  errorServiceUnavailable: 'Service unavailable',
  errorLoading: 'Error loading',
};

export const translations: Record<Lang, typeof nl> = { nl, de, en };
export type T = typeof nl;
