// portal/app/dashboard/lang.ts
export type Lang = 'nl' | 'de' | 'en';

const nl = {
  // Titles
  titleHome: 'Home',
  titleMail: 'Mail',
  titleDocs: 'Documenten',
  titleProfile: 'Profiel',
  titleTasks: 'Taken',
  titleCalendar: 'Agenda',
  titlePhotos: "Foto's",
  titleAssistant: 'AI Assistent',
  titleContacts: 'Contacten',
  titleAdmin: 'Beheer',
  titleFallback: 'Diggi Cloud',
  // Nav
  navHome: 'Home',
  navMail: 'Mail',
  navDocs: 'Docs',
  navProfile: 'Profiel',
  navTasks: 'Taken',
  // Dashboard
  welcome: (name: string) => `Goedemorgen, ${name}`,
  overview: 'Hier is je overzicht voor vandaag',
  statDocs: 'Documenten',
  statMail: 'Ongelezen mail',
  statProcessing: 'In verwerking',
  statTasks: 'Open taken',
  recentActivity: 'Recente activiteit',
  noActivity: 'Nog geen activiteit',
  statusDone: 'Samenvatting verzonden',
  statusProcessing: 'Bezig met verwerken',
  statusPending: 'Wacht op verwerking',
  statusFailed: 'Mislukt',
  timeJustNow: 'zojuist',
  timeMinutes: (m: number) => `${m}m geleden`,
  timeHours: (h: number) => `${h}u geleden`,
  timeDays: (d: number) => `${d}d geleden`,
  searchPlaceholder: 'Zoeken...',
  noResults: 'Geen resultaten',
  noDocs: 'Geen documenten',
  sectionNotifications: 'Meldingen',
  saving: 'opslaan…',
  prefSignalNotify: 'Signal-meldingen',
  prefSignalNotifyDesc: 'Melding bij nieuw document',
  prefDigest: 'Digest-modus',
  prefDigestDesc: 'Dagelijks overzicht i.p.v. direct',
  sectionLanguage: 'Taal',
  adminSettings: 'Beheerdersinstellingen',
  adminSettingsDesc: 'Gebruikers, systeem, configuratie',
  logout: 'Uitloggen',
  // Mail
  mailNoMessages: 'Geen berichten',
  mailLoading: 'Laden…',
  mailConnectionError: 'Verbindingsfout',
  mailLoadError: 'Kon berichten niet laden',
  mailSelectMessage: 'Selecteer een bericht',
  mailUnknown: '(onbekend)',
  mailNoSubject: '(geen onderwerp)',
  mailNoContent: '(geen inhoud)',
  mailFrom: 'Van:',
  mailTo: 'Aan:',
  mailCc: 'CC:',
  mailMoveToTrash: 'Naar prullenbak',
  mailDeleteForever: 'Definitief verwijderen',
  mailCompose: 'Nieuw bericht',
  mailReply: 'Beantwoorden',
  mailForward: 'Doorsturen',
  mailSend: 'Versturen',
  mailSubject: 'Onderwerp',
  mailDraft: 'Concept opgeslagen',
  // Tasks
  tasksOpen: 'Open taken',
  tasksDone: 'Afgerond',
  tasksEmpty: 'Geen openstaande taken',
  tasksDoneEmpty: 'Nog geen afgeronde taken',
  tasksMarkDone: 'Afgerond',
  tasksDelete: 'Verwijder',
  tasksDue: 'Vervaldatum',
  tasksOverdue: 'Te laat',
  tasksAddSignal: 'Stuur /taak <beschrijving> op Signal om een taak aan te maken.',
  // Calendar
  calendarToday: 'Vandaag',
  calendarThisWeek: 'Deze week',
  calendarNoEvents: 'Geen evenementen',
  calendarAdd: 'Toevoegen',
  calendarAllDay: 'Hele dag',
  calendarNewEvent: 'Nieuw evenement',
  calendarTitle: 'Titel',
  calendarStart: 'Start',
  calendarEnd: 'Einde',
  calendarLocation: 'Locatie',
  calendarDescription: 'Beschrijving',
  calendarSave: 'Opslaan',
  calendarCancel: 'Annuleren',
  // Docs
  noArchive: 'Geen archief beschikbaar',
  selectCategory: 'Selecteer een categorie',
  docsUpload: 'Uploaden',
  docsUploadTitle: 'Document uploaden',
  docsSelectFile: 'Bestand selecteren',
  docsUploading: 'Uploaden…',
  docsUploadSuccess: 'Document geüpload',
  docsUploadError: 'Upload mislukt',
  docsAiSummary: 'AI Samenvatting',
  docsAiSummarizing: 'Samenvatten…',
  // Contacts
  contactsEmpty: 'Geen contacten',
  contactsAdd: 'Contact toevoegen',
  contactsName: 'Naam',
  contactsEmail: 'E-mail',
  contactsPhone: 'Telefoon',
  contactsOrg: 'Organisatie',
  contactsSave: 'Opslaan',
  // AI Assistant
  aiPlaceholder: 'Stel een vraag over je documenten, mail of agenda…',
  aiWelcome: 'Hallo! Ik ben je Diggi Cloud assistent. Ik kan je helpen met vragen over je documenten, mail, agenda en meer.',
  aiThinking: 'Denkt na…',
  aiError: 'Antwoord niet ontvangen. Probeer opnieuw.',
  aiClearChat: 'Gesprek wissen',
  aiContextDocs: 'Documenten',
  aiContextMail: 'Mail',
  aiContextCalendar: 'Agenda',
  // Error handling
  errorRetry: 'Opnieuw proberen',
  errorServiceUnavailable: 'Service niet beschikbaar',
  errorLoading: 'Fout bij laden',
};

const de: typeof nl = {
  titleHome: 'Startseite',
  titleMail: 'Mail',
  titleDocs: 'Dokumente',
  titleProfile: 'Profil',
  titleTasks: 'Aufgaben',
  titleCalendar: 'Kalender',
  titlePhotos: 'Fotos',
  titleAssistant: 'KI-Assistent',
  titleContacts: 'Kontakte',
  titleAdmin: 'Verwaltung',
  titleFallback: 'Diggi Cloud',
  navHome: 'Startseite',
  navMail: 'Mail',
  navDocs: 'Dokumente',
  navProfile: 'Profil',
  navTasks: 'Aufgaben',
  welcome: (name: string) => `Guten Morgen, ${name}`,
  overview: 'Hier ist deine Übersicht für heute',
  statDocs: 'Dokumente',
  statMail: 'Ungelesene Mails',
  statProcessing: 'In Bearbeitung',
  statTasks: 'Offene Aufgaben',
  recentActivity: 'Letzte Aktivität',
  noActivity: 'Noch keine Aktivität',
  statusDone: 'Zusammenfassung gesendet',
  statusProcessing: 'Wird verarbeitet',
  statusPending: 'Wartet auf Verarbeitung',
  statusFailed: 'Fehlgeschlagen',
  timeJustNow: 'gerade eben',
  timeMinutes: (m: number) => `vor ${m} Min.`,
  timeHours: (h: number) => `vor ${h} Std.`,
  timeDays: (d: number) => `vor ${d} Tagen`,
  searchPlaceholder: 'Suchen...',
  noResults: 'Keine Ergebnisse',
  noDocs: 'Keine Dokumente',
  sectionNotifications: 'Benachrichtigungen',
  saving: 'speichern…',
  prefSignalNotify: 'Signal-Benachrichtigungen',
  prefSignalNotifyDesc: 'Benachrichtigung bei neuem Dokument',
  prefDigest: 'Digest-Modus',
  prefDigestDesc: 'Tägliche Übersicht statt sofort',
  sectionLanguage: 'Sprache',
  adminSettings: 'Admineinstellungen',
  adminSettingsDesc: 'Benutzer, System, Konfiguration',
  logout: 'Abmelden',
  mailNoMessages: 'Keine Nachrichten',
  mailLoading: 'Laden…',
  mailConnectionError: 'Verbindungsfehler',
  mailLoadError: 'Nachrichten konnten nicht geladen werden',
  mailSelectMessage: 'Nachricht auswählen',
  mailUnknown: '(unbekannt)',
  mailNoSubject: '(kein Betreff)',
  mailNoContent: '(kein Inhalt)',
  mailFrom: 'Von:',
  mailTo: 'An:',
  mailCc: 'CC:',
  mailMoveToTrash: 'In Papierkorb',
  mailDeleteForever: 'Endgültig löschen',
  mailCompose: 'Neue Nachricht',
  mailReply: 'Antworten',
  mailForward: 'Weiterleiten',
  mailSend: 'Senden',
  mailSubject: 'Betreff',
  mailDraft: 'Entwurf gespeichert',
  tasksOpen: 'Offene Aufgaben',
  tasksDone: 'Erledigt',
  tasksEmpty: 'Keine offenen Aufgaben',
  tasksDoneEmpty: 'Noch keine erledigten Aufgaben',
  tasksMarkDone: 'Erledigt',
  tasksDelete: 'Löschen',
  tasksDue: 'Fällig',
  tasksOverdue: 'Überfällig',
  tasksAddSignal: 'Sende /aufgabe <beschreibung> auf Signal um eine Aufgabe zu erstellen.',
  calendarToday: 'Heute',
  calendarThisWeek: 'Diese Woche',
  calendarNoEvents: 'Keine Termine',
  calendarAdd: 'Hinzufügen',
  calendarAllDay: 'Ganzer Tag',
  calendarNewEvent: 'Neuer Termin',
  calendarTitle: 'Titel',
  calendarStart: 'Start',
  calendarEnd: 'Ende',
  calendarLocation: 'Ort',
  calendarDescription: 'Beschreibung',
  calendarSave: 'Speichern',
  calendarCancel: 'Abbrechen',
  noArchive: 'Kein Archiv verfügbar',
  selectCategory: 'Kategorie auswählen',
  docsUpload: 'Hochladen',
  docsUploadTitle: 'Dokument hochladen',
  docsSelectFile: 'Datei auswählen',
  docsUploading: 'Hochladen…',
  docsUploadSuccess: 'Dokument hochgeladen',
  docsUploadError: 'Upload fehlgeschlagen',
  docsAiSummary: 'KI-Zusammenfassung',
  docsAiSummarizing: 'Zusammenfassen…',
  contactsEmpty: 'Keine Kontakte',
  contactsAdd: 'Kontakt hinzufügen',
  contactsName: 'Name',
  contactsEmail: 'E-Mail',
  contactsPhone: 'Telefon',
  contactsOrg: 'Organisation',
  contactsSave: 'Speichern',
  aiPlaceholder: 'Stell eine Frage zu deinen Dokumenten, Mails oder Terminen…',
  aiWelcome: 'Hallo! Ich bin dein Diggi Cloud Assistent. Ich kann dir bei Fragen zu deinen Dokumenten, Mails, Terminen und mehr helfen.',
  aiThinking: 'Denke nach…',
  aiError: 'Keine Antwort erhalten. Bitte erneut versuchen.',
  aiClearChat: 'Chat leeren',
  aiContextDocs: 'Dokumente',
  aiContextMail: 'Mail',
  aiContextCalendar: 'Kalender',
  errorRetry: 'Erneut versuchen',
  errorServiceUnavailable: 'Dienst nicht verfügbar',
  errorLoading: 'Fehler beim Laden',
};

const en: typeof nl = {
  titleHome: 'Home',
  titleMail: 'Mail',
  titleDocs: 'Documents',
  titleProfile: 'Profile',
  titleTasks: 'Tasks',
  titleCalendar: 'Calendar',
  titlePhotos: 'Photos',
  titleAssistant: 'AI Assistant',
  titleContacts: 'Contacts',
  titleAdmin: 'Admin',
  titleFallback: 'Diggi Cloud',
  navHome: 'Home',
  navMail: 'Mail',
  navDocs: 'Docs',
  navProfile: 'Profile',
  navTasks: 'Tasks',
  welcome: (name: string) => `Good morning, ${name}`,
  overview: "Here's your overview for today",
  statDocs: 'Documents',
  statMail: 'Unread mail',
  statProcessing: 'Processing',
  statTasks: 'Open tasks',
  recentActivity: 'Recent activity',
  noActivity: 'No activity yet',
  statusDone: 'Summary sent',
  statusProcessing: 'Processing',
  statusPending: 'Waiting to process',
  statusFailed: 'Failed',
  timeJustNow: 'just now',
  timeMinutes: (m: number) => `${m}m ago`,
  timeHours: (h: number) => `${h}h ago`,
  timeDays: (d: number) => `${d}d ago`,
  searchPlaceholder: 'Search...',
  noResults: 'No results',
  noDocs: 'No documents',
  sectionNotifications: 'Notifications',
  saving: 'saving…',
  prefSignalNotify: 'Signal notifications',
  prefSignalNotifyDesc: 'Alert on new document',
  prefDigest: 'Digest mode',
  prefDigestDesc: 'Daily digest instead of instant',
  sectionLanguage: 'Language',
  adminSettings: 'Admin settings',
  adminSettingsDesc: 'Users, system, configuration',
  logout: 'Sign out',
  mailNoMessages: 'No messages',
  mailLoading: 'Loading…',
  mailConnectionError: 'Connection error',
  mailLoadError: 'Could not load messages',
  mailSelectMessage: 'Select a message',
  mailUnknown: '(unknown)',
  mailNoSubject: '(no subject)',
  mailNoContent: '(no content)',
  mailFrom: 'From:',
  mailTo: 'To:',
  mailCc: 'CC:',
  mailMoveToTrash: 'Move to trash',
  mailDeleteForever: 'Delete permanently',
  mailCompose: 'New message',
  mailReply: 'Reply',
  mailForward: 'Forward',
  mailSend: 'Send',
  mailSubject: 'Subject',
  mailDraft: 'Draft saved',
  tasksOpen: 'Open tasks',
  tasksDone: 'Done',
  tasksEmpty: 'No open tasks',
  tasksDoneEmpty: 'No completed tasks yet',
  tasksMarkDone: 'Mark done',
  tasksDelete: 'Delete',
  tasksDue: 'Due',
  tasksOverdue: 'Overdue',
  tasksAddSignal: 'Send /task <description> on Signal to create a task.',
  calendarToday: 'Today',
  calendarThisWeek: 'This week',
  calendarNoEvents: 'No events',
  calendarAdd: 'Add',
  calendarAllDay: 'All day',
  calendarNewEvent: 'New event',
  calendarTitle: 'Title',
  calendarStart: 'Start',
  calendarEnd: 'End',
  calendarLocation: 'Location',
  calendarDescription: 'Description',
  calendarSave: 'Save',
  calendarCancel: 'Cancel',
  noArchive: 'No archive available',
  selectCategory: 'Select a category',
  docsUpload: 'Upload',
  docsUploadTitle: 'Upload document',
  docsSelectFile: 'Select file',
  docsUploading: 'Uploading…',
  docsUploadSuccess: 'Document uploaded',
  docsUploadError: 'Upload failed',
  docsAiSummary: 'AI Summary',
  docsAiSummarizing: 'Summarizing…',
  contactsEmpty: 'No contacts',
  contactsAdd: 'Add contact',
  contactsName: 'Name',
  contactsEmail: 'Email',
  contactsPhone: 'Phone',
  contactsOrg: 'Organization',
  contactsSave: 'Save',
  aiPlaceholder: 'Ask me about your documents, mail, or calendar…',
  aiWelcome: 'Hi! I\'m your Diggi Cloud assistant. I can help you with questions about your documents, mail, calendar, and more.',
  aiThinking: 'Thinking…',
  aiError: 'No response received. Please try again.',
  aiClearChat: 'Clear chat',
  aiContextDocs: 'Documents',
  aiContextMail: 'Mail',
  aiContextCalendar: 'Calendar',
  errorRetry: 'Try again',
  errorServiceUnavailable: 'Service unavailable',
  errorLoading: 'Error loading',
};

export const translations: Record<Lang, typeof nl> = { nl, de, en };
export type T = typeof nl;
