export enum BootstrapState {
  UNINITIALIZED = 'UNINITIALIZED',
  DNS_CHECK = 'DNS_CHECK',
  CREATING_SECRETS = 'CREATING_SECRETS',
  AUTHENTIK_SETUP = 'AUTHENTIK_SETUP',
  MAILCOW_SETUP = 'MAILCOW_SETUP',
  TRAEFIK_CONFIG = 'TRAEFIK_CONFIG',
  READY = 'READY',
}
