import { Injectable, Logger } from '@nestjs/common';
import * as fs from 'fs/promises';
import * as path from 'path';

export interface TraefikConfig {
  primaryDomain: string;
  mailDomain: string;
  adminEmail: string;
  traefikConfigDir: string;
}

@Injectable()
export class TraefikService {
  private readonly logger = new Logger(TraefikService.name);

  async provision(config: TraefikConfig): Promise<void> {
    this.logger.log('Generating Traefik dynamic config...');

    await fs.mkdir(config.traefikConfigDir, { recursive: true });

    const dynamicConfig = this.generateDynamicConfig(config);
    const configPath = path.join(config.traefikConfigDir, 'platform.yml');
    await fs.writeFile(configPath, dynamicConfig, 'utf-8');

    const staticConfig = this.generateStaticConfig(config);
    const staticPath = path.join(config.traefikConfigDir, 'traefik.yml');
    await fs.writeFile(staticPath, staticConfig, 'utf-8');

    this.logger.log(`Traefik config written to ${configPath}`);
  }

  private generateStaticConfig(config: TraefikConfig): string {
    return `# Generated by platform bootstrap
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${config.adminEmail}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true
`;
  }

  private generateDynamicConfig(config: TraefikConfig): string {
    const { primaryDomain, mailDomain } = config;

    return `# Generated by platform bootstrap — do not edit manually
http:
  routers:
    portal:
      rule: "Host(\`portal.${primaryDomain}\`)"
      entryPoints: [websecure]
      service: portal
      tls:
        certResolver: letsencrypt

    api:
      rule: "Host(\`portal.${primaryDomain}\`) && PathPrefix(\`/api\`)"
      entryPoints: [websecure]
      service: api
      tls:
        certResolver: letsencrypt

    authentik:
      rule: "Host(\`auth.${primaryDomain}\`)"
      entryPoints: [websecure]
      service: authentik
      tls:
        certResolver: letsencrypt

    mailcow:
      rule: "Host(\`mail.${mailDomain}\`)"
      entryPoints: [websecure]
      service: mailcow
      tls:
        certResolver: letsencrypt

  services:
    portal:
      loadBalancer:
        servers:
          - url: "http://portal:3000"

    api:
      loadBalancer:
        servers:
          - url: "http://api:3001"

    authentik:
      loadBalancer:
        servers:
          - url: "http://authentik-server:9000"

    mailcow:
      loadBalancer:
        servers:
          - url: "http://nginx-mailcow:80"
`;
  }
}
